select id,replace(replace(nombre,'o','*'),'O','*') "Nombre",apellidos,fecha_nacimiento,posicion,salario,id_equipo from futbolistas;
insert into futbolistas values ('F80120','MIGUEL','GARCIA','22/02/1980','DEFENSA',350000,1);
select * from futbolistas;
select id,replace(replace(nombre,'e','A'),'E','A') "Nombre",apellidos,fecha_nacimiento,posicion,salario,id_equipo from futbolistas;
select nombre, instr(nombre,length(nombre))"Posicion", trim(substr(concat(nombre,' '),0,instr(concat(nombre,' '),' ')))"Primer Nombre" from futbolistas;
select systimestamp from dual;
select next_day(sysdate, 'MiÉRCOLES') from dual;
select extract(month from to_date('01/02/2020'))"Extracto" from dual;
select extract(day from sysdate),extract(month from sysdate), extract(year from sysdate) from dual;
select ADD_MONTHS(sysdate,6) from dual;
select floor(months_BETWEEN(sysdate, fecha_nacimiento)) from futbolistas;
select last_day(sysdate) from dual;
select next_day(sysdate,'Lunes') from dual;
select sysdate-30 from dual;
select to_char(sysdate,'dd/dd/dd') from dual;
select (select extract(year from(fecha_nacimiento)) from futbolistas where id = 'F00520') - (select EXTRACT(year from (fecha_nacimiento)) from futbolistas where id = 'F00220') "Fecha entre Pedro y Jesus"  from dual;
select * from futbolistas;
select '1000€' - '20€' from dual;
select  concat(to_char(to_number('1000.00€','9999.00L') - to_number('20€','99L')),'€')"Resta" from dual;
select to_char(sysdate, 'MI DAY Month') from dual;
select to_number('-$1000.45', 'S$9999.99') from dual;
select to_char(sysdate,'dd/mm/yyyy') from dual;
select to_char(id,'999') from futbolistas;
select NVL(Salario,0) from futbolistas;
select * from futbolistas;
update futbolistas set salario = NULL where id = 'F00320';
select DECODE(Salario,NULL,'No tiene',110000,'Buen sueldo',salario) from futbolistas;
select DECODE(presupuesto,1000000,'1000K',2000000,'2000K',3000000,'3000K','No existe') from equipos;
select count(*) from futbolistas;
select concat(sum(salario),'€') from futbolistas;
select min(salario) from futbolistas;
select max(salario) from futbolistas;
select round(avg(salario),2) "Salario Medio" from futbolistas;
select posicion from futbolistas group by posicion;
select posicion,count(posicion) from futbolistas group by posicion;
select posicion,count(posicion) from futbolistas where posicion is not null group by posicion;
update futbolistas set posicion = NULL where posicion = 'DELANTERO';
select nombre,salario from futbolistas where salario is not null;
alter table futbolistas add Altura int;
alter table futbolistas add Peso number(4,1);
update futbolistas set altura = 162,Peso = 60 where nombre = 'ENRIQUE';
select * from futbolistas;
select nombre,altura from futbolistas where altura = (select max(altura) from futbolistas);
select apellidos from futbolistas where peso = (select min(peso) from futbolistas);
select count(nombre) from futbolistas where altura >= 175 and altura <= 182;
select round(avg(altura),2) from futbolistas;
select round(avg(peso),1) from futbolistas;
select nombre,salario from futbolistas where salario = (select max(salario) from futbolistas);
select extract(year from fecha_nacimiento) from futbolistas where salario = (select min(salario) from futbolistas);  
select round(avg(salario),2) from futbolistas where salario is not null group by posicion;
select count(id_equipo) from futbolistas group by id_equipo;
select * from equipos;
select count(id_equipo) from futbolistas group by id_equipo having id_equipo in(1,2);--select campos from nombreTabla where condicion group by campos Having condiciones order by campos;
//
//
select * from futbolistas,equipos where id_equipo = equipos.id;
select * from futbolistas;
Insert into futbolistas values ('F90120','PIPO','LUISIANO',null,null,null,null,null,null);
Insert into equipos values (4,null,null,null);
select * from EQUIPOS;
select * from Futbolistas join equipos on equipos.id = futbolistas.id_equipo ;
select * from futbolistas RIGHT join equipos on equipos.id = futbolistas.id_equipo;
select * from futbolistas FULL OUTER join equipos on equipos.id = futbolistas.id_equipo;
select futbolistas.nombre,equipos.nombre from futbolistas join equipos on futbolistas.nombre_equipo;
select futbolistas.nombre,futbolistas.apellidos,equipos.nombre from futbolistas join equipos on futbolistas.id_equipo = equipos.id where futbolistas.posicion = 'DEFENSA';
select futbolistas.salario  from futbolistas union select equipos.presupuesto from equipos;
select estadio from equipos intersect select estadio from partidos;
select estadio from equipos minus select estadio from partidos;
